---
abstract: 'PSGI interface for RPC::Any'
author:
  - 'Sherwin Daganato <sherwin@daganato.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-Any-Interface-PSGI
no_index:
  directory:
    - t
    - inc
requires:
  RPC::Any: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/sherwind/RPC-Any-Interface-PSGI/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/sherwind/RPC-Any-Interface-PSGI.git
version: 0.02
